/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jtasklistmanager;


public class JTaskListManagerFormTest extends javax.swing.JFrame {

    /**
     * Creates new form JTaskListManagerForm
     */
    public JTaskListManagerFormTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        centerPane = new javax.swing.JPanel();
        taskPane1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        taskPane2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        taskPane3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton8 = new javax.swing.JButton();
        taskPane4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        taskPane5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton10 = new javax.swing.JButton();
        taskPane6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jCheckBox6 = new javax.swing.JCheckBox();
        jButton11 = new javax.swing.JButton();
        taskPane7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton12 = new javax.swing.JButton();
        taskPane8 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jCheckBox8 = new javax.swing.JCheckBox();
        jButton13 = new javax.swing.JButton();
        taskPane9 = new javax.swing.JPanel();
        jTextField9 = new javax.swing.JTextField();
        jCheckBox9 = new javax.swing.JCheckBox();
        jButton14 = new javax.swing.JButton();
        taskPane10 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jCheckBox10 = new javax.swing.JCheckBox();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Add Task");
        jPanel4.add(jButton3);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(400, 29));
        jPanel2.add(jComboBox1);

        jButton1.setText("Add Task List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("Save Task List");
        jPanel2.add(jButton2);

        jButton5.setText("Save Task List");
        jPanel2.add(jButton5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        centerPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        centerPane.setLayout(new java.awt.GridLayout(10, 0, 0, 20));

        jTextField1.setText("jTextField1");
        jTextField1.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane1.add(jTextField1);

        jCheckBox1.setText("Done?");
        taskPane1.add(jCheckBox1);

        jButton6.setText("Delete Task");
        taskPane1.add(jButton6);

        centerPane.add(taskPane1);

        jTextField2.setText("jTextField1");
        jTextField2.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane2.add(jTextField2);

        jCheckBox2.setText("Done?");
        taskPane2.add(jCheckBox2);

        jButton7.setText("Delete Task");
        taskPane2.add(jButton7);

        centerPane.add(taskPane2);

        jTextField3.setText("jTextField1");
        jTextField3.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane3.add(jTextField3);

        jCheckBox3.setText("Done?");
        taskPane3.add(jCheckBox3);

        jButton8.setText("Delete Task");
        taskPane3.add(jButton8);

        centerPane.add(taskPane3);

        jTextField4.setText("jTextField1");
        jTextField4.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane4.add(jTextField4);

        jCheckBox4.setText("Done?");
        taskPane4.add(jCheckBox4);

        jButton9.setText("Delete Task");
        taskPane4.add(jButton9);

        centerPane.add(taskPane4);

        jTextField5.setText("jTextField1");
        jTextField5.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane5.add(jTextField5);

        jCheckBox5.setText("Done?");
        taskPane5.add(jCheckBox5);

        jButton10.setText("Delete Task");
        taskPane5.add(jButton10);

        centerPane.add(taskPane5);

        jTextField6.setText("jTextField1");
        jTextField6.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane6.add(jTextField6);

        jCheckBox6.setText("Done?");
        taskPane6.add(jCheckBox6);

        jButton11.setText("Delete Task");
        taskPane6.add(jButton11);

        centerPane.add(taskPane6);

        jTextField7.setText("jTextField1");
        jTextField7.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane7.add(jTextField7);

        jCheckBox7.setText("Done?");
        taskPane7.add(jCheckBox7);

        jButton12.setText("Delete Task");
        taskPane7.add(jButton12);

        centerPane.add(taskPane7);

        jTextField8.setText("jTextField1");
        jTextField8.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane8.add(jTextField8);

        jCheckBox8.setText("Done?");
        taskPane8.add(jCheckBox8);

        jButton13.setText("Delete Task");
        taskPane8.add(jButton13);

        centerPane.add(taskPane8);

        jTextField9.setText("jTextField1");
        jTextField9.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane9.add(jTextField9);

        jCheckBox9.setText("Done?");
        taskPane9.add(jCheckBox9);

        jButton14.setText("Delete Task");
        taskPane9.add(jButton14);

        centerPane.add(taskPane9);

        jTextField10.setText("jTextField1");
        jTextField10.setPreferredSize(new java.awt.Dimension(600, 29));
        taskPane10.add(jTextField10);

        jCheckBox10.setText("Done?");
        taskPane10.add(jCheckBox10);

        jButton15.setText("Delete Task");
        taskPane10.add(jButton15);

        centerPane.add(taskPane10);

        jScrollPane2.setViewportView(centerPane);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 871, 615);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JTaskListManagerFormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JTaskListManagerFormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JTaskListManagerFormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JTaskListManagerFormTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTaskListManagerFormTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel taskPane1;
    private javax.swing.JPanel taskPane10;
    private javax.swing.JPanel taskPane2;
    private javax.swing.JPanel taskPane3;
    private javax.swing.JPanel taskPane4;
    private javax.swing.JPanel taskPane5;
    private javax.swing.JPanel taskPane6;
    private javax.swing.JPanel taskPane7;
    private javax.swing.JPanel taskPane8;
    private javax.swing.JPanel taskPane9;
    // End of variables declaration//GEN-END:variables
}
