/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package colorchooser;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author 01613273
 */
public class JInputPanel extends javax.swing.JPanel implements ColorListener {
    
    private Vector listeners;
    public static int red;
    public static int green;
    public static int blue;
    
    
    /**
     * Creates new form JInputPanel
     */
    public JInputPanel() {
        initComponents();
        listeners = new Vector();
        blue  =txtBlue.getValue();
        green =txtGreen.getValue();
        red   =txtRed.getValue();
        
//        sldRe.addActionListener(new ActionListener() {
//      public void actionPerformed(ActionEvent e) {
//        
//      }});
    
    
    }
    

    
    
    public void fireColorEvent(ColorEvent colorEvent){
        Vector v;
        synchronized(this){
            v = (Vector)listeners.clone();
        }
        int size = v.size();
        for(int i=0; i<size; i++){
            ColorListener colorListener = (ColorListener)v.elementAt(i);
            colorListener.changeColor(colorEvent);
        }
    }
    
    public void addColorListener(ColorListener colorListener){
        listeners.addElement(colorListener);
    }
    
    public void removeColorListener(ColorListener colorListener){
        listeners.removeElement(colorListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRed = new colorchooser.JColorNumberFieldRed();
        jLabel2 = new javax.swing.JLabel();
        txtGreen = new colorchooser.JColorNumberFieldGreen();
        jLabel3 = new javax.swing.JLabel();
        txtBlue = new colorchooser.JColorNumberFieldBlue();

        setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jLabel1.setText("Red");
        add(jLabel1);

        txtRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRedActionPerformed(evt);
            }
        });
        add(txtRed);

        jLabel2.setText("Green");
        add(jLabel2);

        txtGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGreenActionPerformed(evt);
            }
        });
        add(txtGreen);

        jLabel3.setText("Blue");
        add(jLabel3);

        txtBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlueActionPerformed(evt);
            }
        });
        add(txtBlue);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRedActionPerformed
        
        try{
               red = txtRed.getValue(); 
            }catch(NumberFormatException e ){
                
                red = 0;
                //System.out.println("empty");

            }
        
         
         blue = txtBlue.getValue();
          green = txtGreen.getValue();
           if((red > 255) || (red < 0)){
               red = 0;
               txtRed.setText(String.valueOf(red));
           }
           
         
        Color color = new Color(red,green,blue);
        fireColorEvent(new ColorEvent(this,color));
    }//GEN-LAST:event_txtRedActionPerformed

    private void txtGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGreenActionPerformed
         try{
               green = txtGreen.getValue();
            }catch(NumberFormatException e ){
                
                green = 0;
                //System.out.println("empty");

            }
         
        
        red = txtRed.getValue();
         blue = txtBlue.getValue();
          
           if((green > 255) || (green < 0)){
              green = 0;
               txtGreen.setText(String.valueOf(green));
           }
        Color color = new Color(red,green,blue);
        fireColorEvent(new ColorEvent(this,color));
    }//GEN-LAST:event_txtGreenActionPerformed

    private void txtBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlueActionPerformed
          try{
                blue = txtBlue.getValue();
            }catch(NumberFormatException e ){
                
                blue = 0;
                //System.out.println("empty");

            } 
        
        
        red = txtRed.getValue();
        
          green = txtGreen.getValue();
           if((blue > 255) || (blue < 0)){
               blue = 0;
               txtBlue.setText(String.valueOf(blue));
           }
        Color color = new Color(red,green,blue);
        fireColorEvent(new ColorEvent(this,color));
    }//GEN-LAST:event_txtBlueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private colorchooser.JColorNumberFieldBlue txtBlue;
    public colorchooser.JColorNumberFieldGreen txtGreen;
    private colorchooser.JColorNumberFieldRed txtRed;
    // End of variables declaration//GEN-END:variables

    @Override
    public void changeColor(ColorEvent ce) {
       
        txtRed.setText(""+ ce.getColor().getRed());
        txtGreen.setText(""+ ce.getColor().getGreen());
        txtBlue.setText(""+ ce.getColor().getBlue());
      
        
    }
    
   
}
