/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shapes;

import javax.swing.JOptionPane;

/**
 *
 * @author 01603857
 */
public class ShapesGUI extends javax.swing.JFrame {

    /**
     * Creates new form ShapeSGUI
     */
    public ShapesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        circleRadioButton = new javax.swing.JRadioButton();
        cylinderRadioButton = new javax.swing.JRadioButton();
        rectRadioButton = new javax.swing.JRadioButton();
        rectPrismRadioButton = new javax.swing.JRadioButton();
        triangleRadioButton = new javax.swing.JRadioButton();
        triPrismRadioButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtField1 = new javax.swing.JTextField();
        txtField2 = new javax.swing.JTextField();
        txtField3 = new javax.swing.JTextField();
        txtField4 = new javax.swing.JTextField();
        lblResults = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sphereRBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Calculating the Shapes");

        buttonGroup1.add(circleRadioButton);
        circleRadioButton.setText("Circle");
        circleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(cylinderRadioButton);
        cylinderRadioButton.setText("Cylinder");
        cylinderRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cylinderRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rectRadioButton);
        rectRadioButton.setText("Rectangle");
        rectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(rectPrismRadioButton);
        rectPrismRadioButton.setText("Rectangular Prisme");
        rectPrismRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectPrismRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(triangleRadioButton);
        triangleRadioButton.setText("Triangle");
        triangleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(triPrismRadioButton);
        triPrismRadioButton.setText("Triangle Prism");
        triPrismRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triPrismRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Please  Enter Data for different shapes:");

        txtField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField1ActionPerformed(evt);
            }
        });

        txtField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField2ActionPerformed(evt);
            }
        });

        txtField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField3ActionPerformed(evt);
            }
        });

        txtField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtField4ActionPerformed(evt);
            }
        });

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("For Circle Radius:");

        jLabel4.setText("For Cylinder Radius and Height:");

        jLabel5.setText("For Rectangle Length and Width:");

        jLabel6.setText("For Rectangular Prisme,Triangle,and Triangle Prisme: ");

        jLabel7.setText("XX means - you do not have to enter the values");

        sphereRBtn.setText("Sphere");
        sphereRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphereRBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("The user must re-click on the selected shape in order to choose the different shapes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(circleRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cylinderRadioButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jButton3)
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rectRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rectPrismRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(triangleRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(triPrismRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sphereRBtn))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtField1, txtField2, txtField3, txtField4});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(circleRadioButton)
                    .addComponent(cylinderRadioButton)
                    .addComponent(rectRadioButton)
                    .addComponent(rectPrismRadioButton)
                    .addComponent(triangleRadioButton)
                    .addComponent(triPrismRadioButton)
                    .addComponent(sphereRBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {circleRadioButton, cylinderRadioButton, rectPrismRadioButton, rectRadioButton, triPrismRadioButton, triangleRadioButton});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtField1, txtField2, txtField3, txtField4});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void circleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleRadioButtonActionPerformed
       if(circleRadioButton.isSelected()){
           txtField2.setText("XX");
           txtField3.setText("XX");
          txtField4.setText("XX");
       }
    }//GEN-LAST:event_circleRadioButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
                 if(circleRadioButton.isSelected()){ 
          Circle circle = new Circle(Double.parseDouble(txtField1.getText()));
          lblResults.setText(circle.toString());
     
                 }
                 
                 else    if(sphereRBtn.isSelected()){ 
                     Sphere sphere = new Sphere(Double.parseDouble(txtField1.getText()));
                     lblResults.setText(sphere.toString());
        try {
           Sphere s = new Sphere(Double.parseDouble(txtField1.getText()));
            lblResults.setText("Surface Area: " + s.getSurfaceArea()+ " Volume: " + s.getVolume());
        }
        catch(NumberFormatException e) 
        {
                JOptionPane.showMessageDialog(null, "Error! Please enter an input of number form.");
              txtField1.setText("");
        } 
   
                 }
                 
                else if (cylinderRadioButton.isSelected()) {       
          double radius = Double.parseDouble(txtField1.getText());
            double height = Double.parseDouble(txtField2.getText());
            Cylinder cylin =new Cylinder(radius,height);
            lblResults.setText(cylin.toString());  
             }
                else if(rectRadioButton.isSelected()){
                
              double length = Double.parseDouble(txtField1.getText());
              double width = Double.parseDouble(txtField2.getText());
             Rectangle rectangle = new Rectangle(length, width);
             lblResults.setText(rectangle.toString());
                
                }
                else if(rectPrismRadioButton.isSelected()){
             double length = Double.parseDouble(txtField1.getText());
            double width = Double.parseDouble(txtField2.getText());
            double height = Double.parseDouble(txtField3.getText());
            RectangularPrism  rectPrism = new RectangularPrism(length,width,height);
            lblResults.setText(rectPrism.toString());
               }
                else if(triangleRadioButton.isSelected()){
                double side1 = Double.parseDouble(txtField1.getText());
                double side2 = Double.parseDouble(txtField2.getText());
                double side3 = Double.parseDouble(txtField3.getText()); 
                Triangle triag = new Triangle(side1,side2,side3);
                lblResults.setText(triag.toString());
                }
                else if (triPrismRadioButton.isSelected()){
                        
                 double side1 = Double.parseDouble(txtField1.getText());
                 double side2 = Double.parseDouble(txtField2.getText());
                 double side3 = Double.parseDouble(txtField3.getText());
                 double height = Double.parseDouble(txtField4.getText());
                 TrianglePrism triangP = new TrianglePrism(side1,side2,side3,height);
                 lblResults.setText(triangP.toString());  
                
                  }
        
            }catch(Exception ex){
     JOptionPane.showMessageDialog(null,"Please enter positive number only ;");
      
      }                       
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cylinderRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cylinderRadioButtonActionPerformed
         if(cylinderRadioButton.isSelected())
         { txtField3.setText("XX");
          txtField4.setText("XX");}
    }//GEN-LAST:event_cylinderRadioButtonActionPerformed

    private void rectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectRadioButtonActionPerformed
        if(rectRadioButton.isSelected()){
            txtField3.setText("XX");
            txtField4.setText("XX");
            
      }
    }//GEN-LAST:event_rectRadioButtonActionPerformed

    private void rectPrismRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectPrismRadioButtonActionPerformed
       if(rectPrismRadioButton.isSelected()){
        txtField4.setText("XX");
       
       }
    }//GEN-LAST:event_rectPrismRadioButtonActionPerformed

    private void triangleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleRadioButtonActionPerformed
       if(triangleRadioButton.isSelected()){
        txtField4.setText("XX");
       }
    }//GEN-LAST:event_triangleRadioButtonActionPerformed
   
    
    private void triPrismRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triPrismRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_triPrismRadioButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtField1.setText("");
        txtField2.setText("");
        txtField3.setText("");
        txtField4.setText(""); 
       
        circleRadioButton.setSelected(false);
        cylinderRadioButton.setSelected(false);
        rectRadioButton.setSelected(false);
        rectPrismRadioButton.setSelected(false);
        triangleRadioButton.setSelected(false);
        triPrismRadioButton.setSelected(false);
         sphereRBtn.setSelected(false);
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField2ActionPerformed

    private void txtField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField3ActionPerformed

    private void txtField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField4ActionPerformed

    private void sphereRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphereRBtnActionPerformed
        // TODO add your handling code here:
           if(sphereRBtn.isSelected()){
           txtField2.setText("XX");
           txtField3.setText("XX");
           txtField4.setText("XX");
       }
    }//GEN-LAST:event_sphereRBtnActionPerformed

    private void txtField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton circleRadioButton;
    private javax.swing.JRadioButton cylinderRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResults;
    private javax.swing.JRadioButton rectPrismRadioButton;
    private javax.swing.JRadioButton rectRadioButton;
    private javax.swing.JRadioButton sphereRBtn;
    private javax.swing.JRadioButton triPrismRadioButton;
    private javax.swing.JRadioButton triangleRadioButton;
    private javax.swing.JTextField txtField1;
    private javax.swing.JTextField txtField2;
    private javax.swing.JTextField txtField3;
    private javax.swing.JTextField txtField4;
    // End of variables declaration//GEN-END:variables
}
